name: json_annotation
version: 4.0.0
description: >-
  Classes and helper functions that support JSON code generation via the
  `json_serializable` package.
homepage: https://github.com/google/json_serializable.dart
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.2.3

# When changing JsonSerializable class.
# dev_dependencies:
#   build_runner: ^1.0.0
#   json_serializable: ^3.1.0
