name: json_serializable
version: 3.5.1
description: >-
  Automatically generate code for converting to and from JSON by annotating
  Dart classes.
repository: https://github.com/google/json_serializable.dart
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  json_annotation: ^4.0.0
  meta: ^1.2.3
  path: ^1.8.0
  source_gen: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.4

dependency_overrides:
  json_annotation:
    path: /home/user/StudioProjects/json_serializable.dart/json_annotation